# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/mowentianxia/android_kernel_xiaomi_latte
          kernel-dir: msm-4.19
          kernel-branch: cm-12.1
          config: lineageos_latte_defconfig
          arch: x86
          aosp-gcc: true
          aosp-clang: true
          android-version: 5.1
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
